### ISSUE TITLE
[question] Is it possible to use this border with other types of windows? (wofi, waybar, mako)

### ISSUE THREAD

**Issue by shaunsingh** [fluix-dev/sway-borders#42] opened 2021-08-28 19:46 UTC
Hi, Ideally I would to have the same border for everything, and have it controlled through my sway config. Is it possible to tell sway to give wofi/waybar/mako to use borders as well?

**Comment by fluix-dev** [comment] 2021-11-05 16:48
No. The same windows that get Sway's normal borders get the custom borders. My own solution is to just customize the borders to match which is generally possible because they use GTK and my rounded borders are just a solid color with an outline.

I'll take a look at how difficult it would be to make a customization option to determine the kinds of windows which get borders (though I'll have to think about the implications of Sway's normal borders as well since they're a bit different).

**Comment by fluix-dev** [comment] 2021-11-05 17:03
Duplicate of #31

**Closed by fluix-dev** 2021-11-05 17:03 UTC
Labels: enhancement
